// src/data.js
export const homeProductData = [
  {
    _id: "1",
    img: "../Image/perfum-1.jpeg",
    scents: "The Legend",
    name: "Finest Classical - Modern Combo",
    price: 1290,
    originalPrice: 1250,
    description: "A classic and modern fragrance combo for all occasions.",
    sku: "SNS001",
    type: "Eau de Parfum",
    vendor: "Scents N Stories",
  },
  {
    _id: "2",
    img: "../Image/perfum-7.jpeg",
    scents: "Merry Me",
    name: "#1 Women's Best Seller",
    price: 1690,
    originalPrice: 1890,
    description: "A top floral scent for women, perfect for special moments.",
    sku: "SNS002",
    type: "Perfume",
    vendor: "Scents N Stories",
  },
  {
    _id: "3",
    img: "../Image/perfum-2.jpg",
    scents: "Da Vinci Code",
    name: "A Gentleman's Favorite",
    price: 1480,
    originalPrice: 1650,
    description: "A sophisticated scent tailored for gentlemen.",
    sku: "SNS003",
    type: "Eau de Toilette",
    vendor: "Scents N Stories",
  },
  {
    _id: "4",
    img: "../Image/perfum-3.jpg",
    scents: "The Notebook",
    name: "3rd Best Selling Soft Floral",
    price: 1440,
    originalPrice: 1690,
    description: "A soft floral fragrance with a romantic touch.",
    sku: "SNS004",
    type: "Eau de Parfum",
    vendor: "Scents N Stories",
  },
  {
    _id: "5",
    img: "../Image/perfum-4.jpg",
    scents: "Dauntless",
    name: "World's 2nd Best Selling DNA",
    price: 1350,
    originalPrice: 1590,
    description: "A bold and unique fragrance with global appeal.",
    sku: "SNS005",
    type: "Cologne",
    vendor: "Scents N Stories",
  },
];
export const bestSellerProductData = [
  {
    _id: "1",
    img: "../Image/perfum-1.jpeg",
    scents: "The Legend",
    name: "Finest Classical - Modern Combo",
    price: 1290,
    originalPrice: 1250,
    description: "A classic and modern fragrance combo for all occasions.",
    sku: "SNS001",
    type: "Eau de Parfum",
    vendor: "Scents N Stories",
  },
  {
    _id: "2",
    img: "../Image/perfum-7.jpeg",
    scents: "Merry Me",
    name: "#1 Women's Best Seller",
    price: 1690,
    originalPrice: 1890,
    description: "A top floral scent for women, perfect for special moments.",
    sku: "SNS002",
    type: "Perfume",
    vendor: "Scents N Stories",
  },
  {
    _id: "3",
    img: "../Image/perfum-2.jpg",
    scents: "Da Vinci Code",
    name: "A Gentleman's Favorite",
    price: 1480,
    originalPrice: 1650,
    description: "A sophisticated scent tailored for gentlemen.",
    sku: "SNS003",
    type: "Eau de Toilette",
    vendor: "Scents N Stories",
  },
  {
    _id: "4",
    img: "../Image/perfum-3.jpg",
    scents: "The Notebook",
    name: "3rd Best Selling Soft Floral",
    price: 1440,
    originalPrice: 1690,
    description: "A soft floral fragrance with a romantic touch.",
    sku: "SNS004",
    type: "Eau de Parfum",
    vendor: "Scents N Stories",
  },
  {
    _id: "5",
    img: "../Image/perfum-4.jpg",
    scents: "Dauntless",
    name: "World's 2nd Best Selling DNA",
    price: 1350,
    originalPrice: 1590,
    description: "A bold and unique fragrance with global appeal.",
    sku: "SNS005",
    type: "Cologne",
    vendor: "Scents N Stories",
  },
];



export const faqs = [
  {
    question: "What types of perfumes do you offer?",
    answer:
      "We offer a wide range of perfumes including floral, woody, oriental, and fresh scents. Our collection caters to both men and women.",
  },
  {
    question: "How long does the perfume last?",
    answer:
      "The longevity of our perfumes varies depending on the type and concentration. Eau de Parfum typically lasts 6-8 hours, while Eau de Toilette lasts 4-6 hours.",
  },
  {
    question: "Do you offer international shipping?",
    answer:
      "Yes, we offer international shipping to most countries. Shipping costs and delivery times may vary depending on your location.",
  },
  {
    question: "Can I return or exchange a perfume?",
    answer:
      "Yes, we have a 30-day return and exchange policy. Please ensure the product is unused and in its original packaging.",
  },
  {
    question: "How do I choose the right perfume for me?",
    answer:
      "Choosing the right perfume depends on your personal preference and the occasion. We recommend trying out samples or reading our detailed fragrance notes to find the perfect match.",
  },
];
export const contactData = [
  {
    id: 1,
    icon: "FaMapMarkerAlt", // Use the icon name as a string
    title: "Address",
    details: ["Copley, South Australia 5732, Australia."],
  },
  {
    id: 2,
    icon: "FiPhoneCall", // Use the icon name as a string
    title: "Call us",
    details: ["+ (02) 6171 3859", "+ (07) 4088 1324"],
  },
  {
    id: 3,
    icon: "FaClock", // Use the icon name as a string
    title: "Open",
    details: ["Monday - Friday: 8am - 4pm", "Saturday - Sunday: 9am - 5pm"],
  },
  {
    id: 4,
    icon: "FaEnvelope", // Use the icon name as a string
    title: "Emails",
    details: ["example@example.com", "example@example.com"],
  },
];

export const contactFaq = [
  {
    question: "How long will shipping take?",
    answer:
      "All orders are shipped within 12-36 hours from our warehouse in Bellingham WA.  Delivery times will depend on your shipping option but all orders are tracked from our facility to your door.  ",
  },
  {
    question: "How do I know if my order is confirmed?",
    answer:
      "This is an example of a response that you might give. It's good to be as thorough as possible in responses as that has a tendency to improve trust overall.",
  },
  {
    question: "Can I change my shipping address after my order is placed?",
    answer:
      "This is an example of a response that you might give. It's good to be as thorough as possible in responses as that has a tendency to improve trust overall",
  },
  
];




export const shopProductData = [
  {
    _id: "101",
    img: "../Image/perfum-7.jpeg",
    scents: "Floral",
    name: "Rose Petal Whisper",
    price: 89.99,
    originalPrice: 120.00,
    description: "A delicate floral fragrance with Bulgarian rose and jasmine absolute",
    sku: "FLR001",
    type: "Eau de Parfum",
    vendor: "Luxury Scents",
    rating: 4.8,
    reviews: 142,
    size: "100ml",
    stock: 15,
    notes: ["Rose", "Jasmine", "Peony", "Musk"],
    concentration: "High",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Romantic"],
    isNew: true,
    isBestSeller: true
  },
  {
    _id: "102",
    img: "../Image/perfum-7.jpeg",
    scents: "Woody",
    name: "Sandalwood Mystique",
    price: 109.99,
    originalPrice: 135.00,
    description: "Rich sandalwood and cedar with vanilla undertones",
    sku: "WDY002",
    type: "Eau de Parfum",
    vendor: "Woodland Aromas",
    rating: 4.6,
    reviews: 89,
    size: "50ml",
    stock: 8,
    notes: ["Sandalwood", "Cedar", "Vanilla", "Amber"],
    concentration: "Medium",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "103",
    img: "../Image/perfum-7.jpeg",
    scents: "Citrus",
    name: "Bergamot Sunrise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Bright citrus blend with TRIMbergamot and lemon zest",
    sku: "CTR003",
    type: "Eau de Toilette",
    vendor: "Citrus Grove",
    rating: 4.5,
    reviews: 76,
    size: "100ml",
    stock: 12,
    notes: ["Bergamot", "Lemon", "Neroli", "Amber"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: true,
    isBestSeller: false
  },
  {
    _id: "104",
    img: "../Image/perfum-7.jpeg",
    scents: "Oriental",
    name: "Amber Nights",
    price: 119.99,
    originalPrice: 145.00,
    description: "Warm oriental scent with amber and vanilla",
    sku: "ORN004",
    type: "Eau de Parfum",
    vendor: "Exotic Essence",
    rating: 4.7,
    reviews: 98,
    size: "50ml",
    stock: 5,
    notes: ["Amber", "Vanilla", "Tonka Bean", "Patchouli"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Romantic"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "105",
    img: "../Image/perfum-7.jpeg",
    scents: "Fresh",
    name: "Ocean Breeze",
    price: 69.99,
    originalPrice: 85.00,
    description: "Crisp aquatic fragrance with sea salt and ozone",
    sku: "FRS005",
    type: "Eau de Toilette",
    vendor: "Aqua Scents",
    rating: 4.3,
    reviews: 64,
    size: "100ml",
    stock: 20,
    notes: ["Sea Salt", "Ozone", "Driftwood", "Musk"],
    concentration: "Light",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "106",
    img: "../Image/perfum-7.jpeg",
    scents: "Gourmand",
    name: "Vanilla Dream",
    price: 94.99,
    originalPrice: 110.00,
    description: "Sweet vanilla with caramel and praline",
    sku: "GRM006",
    type: "Eau de Parfum",
    vendor: "Sweet Scents",
    rating: 4.9,
    reviews: 132,
    size: "50ml",
    stock: 3,
    notes: ["Vanilla", "Caramel", "Praline", "Tonka Bean"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Romantic"],
    isNew: true,
    isBestSeller: true
  },
  {
    _id: "107",
    img: "../Image/perfum-7.jpeg",
    scents: "Aromatic",
    name: "Lavender Fields",
    price: 74.99,
    originalPrice: 90.00,
    description: "Herbal lavender with rosemary and thyme",
    sku: "ARM007",
    type: "Eau de Toilette",
    vendor: "Herbal Essence",
    rating: 4.4,
    reviews: 57,
    size: "100ml",
    stock: 18,
    notes: ["Lavender", "Rosemary", "Thyme", "Oakmoss"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "108",
    img: "../Image/perfum-7.jpeg",
    scents: "Chypre",
    name: "Mossy Woods",
    price: 104.99,
    originalPrice: 125.00,
    description: "Classic chypre with oakmoss and bergamot",
    sku: "CHP008",
    type: "Eau de Parfum",
    vendor: "Vintage Scents",
    rating: 4.6,
    reviews: 82,
    size: "50ml",
    stock: 7,
    notes: ["Oakmoss", "Bergamot", "Patchouli", "Labdanum"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "109",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Berry Delight",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy berry blend with blackcurrant and raspberry",
    sku: "FRT009",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 71,
    size: "100ml",
    stock: 14,
    notes: ["Blackcurrant", "Raspberry", "Peach", "Vanilla"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: true,
    isBestSeller: false
  },
  {
    _id: "110",
    img: "../Image/perfum-7.jpeg",
    scents: "Aquatic",
    name: "Sea Spray",
    price: 69.99,
    originalPrice: 85.00,
    description: "Fresh marine scent with seaweed and salt",
    sku: "AQT010",
    type: "Eau de Toilette",
    vendor: "Oceanic Scents",
    rating: 4.2,
    reviews: 49,
    size: "100ml",
    stock: 22,
    notes: ["Seaweed", "Salt", "Driftwood", "Ambergris"],
    concentration: "Light",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "111",
    img: "../Image/perfum-7.jpeg",
    scents: "Spicy",
    name: "Cinnamon Fire",
    price: 99.99,
    originalPrice: 120.00,
    description: "Warm spicy fragrance with cinnamon and clove",
    sku: "SPY011",
    type: "Eau de Parfum",
    vendor: "Spice Market",
    rating: 4.7,
    reviews: 88,
    size: "50ml",
    stock: 6,
    notes: ["Cinnamon", "Clove", "Vanilla", "Amber"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "112",
    img: "../Image/perfum-7.jpeg",
    scents: "Leather",
    name: "Suede & Smoke",
    price: 114.99,
    originalPrice: 135.00,
    description: "Rich leather with smoky birch and tobacco",
    sku: "LTH012",
    type: "Eau de Parfum",
    vendor: "Luxury Scents",
    rating: 4.8,
    reviews: 94,
    size: "50ml",
    stock: 4,
    notes: ["Leather", "Birch", "Tobacco", "Vanilla"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "113",
    img: "../Image/perfum-7.jpeg",
    scents: "Floral",
    name: "Jasmine Bloom",
    price: 89.99,
    originalPrice: 110.00,
    description: "Intoxicating jasmine with orange blossom",
    sku: "FLR013",
    type: "Eau de Parfum",
    vendor: "Floral Essence",
    rating: 4.6,
    reviews: 78,
    size: "100ml",
    stock: 10,
    notes: ["Jasmine", "Orange Blossom", "Tuberose", "Musk"],
    concentration: "High",
    season: ["Spring", "Summer"],
    occasion: ["Evening", "Romantic"],
    isNew: true,
    isBestSeller: false
  },
  {
    _id: "114",
    img: "../Image/perfum-7.jpeg",
    scents: "Woody",
    name: "Cedar Supreme",
    price: 104.99,
    originalPrice: 125.00,
    description: "Majestic cedar with vetiver and patchouli",
    sku: "WDY014",
    type: "Eau de Parfum",
    vendor: "Woodland Aromas",
    rating: 4.7,
    reviews: 86,
    size: "50ml",
    stock: 5,
    notes: ["Cedar", "Vetiver", "Patchouli", "Amber"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "115",
    img: "../Image/perfum-7.jpeg",
    scents: "Citrus",
    name: "Lemon Zest",
    price: 74.99,
    originalPrice: 90.00,
    description: "Zesty lemon with bergamot and grapefruit",
    sku: "CTR015",
    type: "Eau de Toilette",
    vendor: "Citrus Grove",
    rating: 4.4,
    reviews: 62,
    size: "100ml",
    stock: 16,
    notes: ["Lemon", "Bergamot", "Grapefruit", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "116",
    img: "../Image/perfum-7.jpeg",
    scents: "Oriental",
    name: "Oud Mystique",
    price: 129.99,
    originalPrice: 150.00,
    description: "Luxurious oud with rose and saffron",
    sku: "ORN016",
    type: "Perfume Oil",
    vendor: "Exotic Essence",
    rating: 4.9,
    reviews: 112,
    size: "30ml",
    stock: 2,
    notes: ["Oud", "Rose", "Saffron", "Amber"],
    concentration: "Very High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: true,
    isBestSeller: true
  },
  {
    _id: "117",
    img: "../Image/perfum-7.jpeg",
    scents: "Fresh",
    name: "Mountain Air",
    price: 69.99,
    originalPrice: 85.00,
    description: "Crisp alpine scent with pine and juniper",
    sku: "FRS017",
    type: "Eau de Toilette",
    vendor: "Nature Scents",
    rating: 4.3,
    reviews: 53,
    size: "100ml",
    stock: 19,
    notes: ["Pine", "Juniper", "Mint", "Amber"],
    concentration: "Light",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "118",
    img: "../Image/perfum-7.jpeg",
    scents: "Gourmand",
    name: "Chocolate Truffle",
    price: 94.99,
    originalPrice: 110.00,
    description: "Decadent chocolate with vanilla and caramel",
    sku: "GRM018",
    type: "Eau de Parfum",
    vendor: "Sweet Scents",
    rating: 4.8,
    reviews: 97,
    size: "50ml",
    stock: 4,
    notes: ["Chocolate", "Vanilla", "Caramel", "Tonka Bean"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Romantic"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "119",
    img: "../Image/perfum-7.jpeg",
    scents: "Aromatic",
    name: "Herbal Garden",
    price: 74.99,
    originalPrice: 90.00,
    description: "Fresh herbs with lavender and rosemary",
    sku: "ARM019",
    type: "Eau de Toilette",
    vendor: "Herbal Essence",
    rating: 4.4,
    reviews: 58,
    size: "100ml",
    stock: 17,
    notes: ["Lavender", "Rosemary", "Thyme", "Oakmoss"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: true,
    isBestSeller: false
  },
  {
    _id: "120",
    img: "../Image/perfum-7.jpeg",
    scents: "Chypre",
    name: "Vintage Moss",
    price: 104.99,
    originalPrice: 125.00,
    description: "Classic chypre with oakmoss and bergamot",
    sku: "CHP020",
    type: "Eau de Parfum",
    vendor: "Vintage Scents",
    rating: 4.6,
    reviews: 81,
    size: "50ml",
    stock: 6,
    notes: ["Oakmoss", "Bergamot", "Patchouli", "Labdanum"],
    concentration: "High",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Formal"],
    isNew: false,
    isBestSeller: true
  },
  {
    _id: "121",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "122",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "123",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "124",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "125",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "126",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "127",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "128",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "129",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "130",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "131",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "132",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "133",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "134",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "135",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "136",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "137",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "138",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "139",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "140",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "141",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "142",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "143",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "144",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "145",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "146",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "147",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "148",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "149",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
  {
    _id: "150",
    img: "../Image/perfum-7.jpeg",
    scents: "Fruity",
    name: "Peach Paradise",
    price: 79.99,
    originalPrice: 95.00,
    description: "Juicy peach with apricot and vanilla",
    sku: "FRT021",
    type: "Eau de Toilette",
    vendor: "Fruitful Scents",
    rating: 4.5,
    reviews: 69,
    size: "100ml",
    stock: 13,
    notes: ["Peach", "Apricot", "Vanilla", "Musk"],
    concentration: "Medium",
    season: ["Spring", "Summer"],
    occasion: ["Daytime", "Casual"],
    isNew: false,
    isBestSeller: false
  },
];




